/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui.Master.BrowseAll;
import dao.KategoriDAO;
import model.Kategori;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.util.List;
import ui.Master.frmBarang;
import ui.Master.frmKategori;

/**
 *
 * @author Admin
 */
public class BrowseKategoriDialog extends javax.swing.JDialog {
    private KategoriDAO kategoriDAO;
    private DefaultTableModel tableModel;
    private List<Kategori> kategoriList;

    /**
     * Creates new form BrowseKategoriDialog
     */
    public BrowseKategoriDialog(java.awt.Frame parent, boolean modal, Connection conn) {
        super(parent, modal);
        initComponents();
        this.kategoriDAO = new KategoriDAO(conn);
        setupTable();
        loadData();
        setLocationRelativeTo(null);
         setupTableClickListener();
         jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }
     private void setupTable() {
        String[] columnNames = {"ID", "Kode", "Nama", "Deskripsi", "Is Aktif"};
        tableModel = new DefaultTableModel(columnNames, 0);
        jTable1.setModel(tableModel);
    }
     private void setupTableClickListener() {
        jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() >= 1) { // Detect double click
                    selectRowAndClose();
                }
            }
        });
    }

    private void loadData() {
        kategoriList = kategoriDAO.getAllKategori();
        updateTable(kategoriList);
    }

    private void updateTable(List<Kategori> kategoriList) {
        tableModel.setRowCount(0); // Reset table model

        for (Kategori kategori : kategoriList) {
            Object[] row = {
                kategori.getId(),
                kategori.getKode(),
                kategori.getNama(),
                kategori.getDeskripsi(),
                kategori.isAktif() ? "Ya" : "Tidak"
            };
            tableModel.addRow(row);
        }
    }

private void selectRowAndClose() {
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow >= 0)  {
            String selectedID = jTable1.getValueAt(selectedRow, 0).toString(); // ID
            String selectedKode = jTable1.getValueAt(selectedRow, 1).toString(); // Kode
            String selectedNama = jTable1.getValueAt(selectedRow, 2).toString(); // Nama
            String selectedKeterangan = jTable1.getValueAt(selectedRow, 3).toString(); // Deskripsi
            boolean isAktif = "Ya".equalsIgnoreCase(jTable1.getValueAt(selectedRow, 4).toString()); // Is Aktif

            // Set values to the components in the parent form (example)
            // Assuming you have a method to set these in your main form
           if (getParent() instanceof frmKategori) {
            ((frmKategori) getParent()).setKategoriData(selectedID, selectedKode, selectedNama, selectedKeterangan, isAktif);
        } else if (getParent() instanceof frmBarang) {
            ((frmBarang) getParent()).setKategoriData(selectedID, selectedKode, selectedNama);
        }
            // Close the dialog
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Please select a category.", "No selection", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void searchKategori() {
        String keyword = jTextField1.getText().trim();
        kategoriList = kategoriDAO.searchKategoriByName(keyword);
        updateTable(kategoriList);
    }
    public JTable getTable() {
        return jTable1;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Browse Kategori");
        setMaximumSize(new java.awt.Dimension(464, 245));
        setMinimumSize(new java.awt.Dimension(464, 245));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-add-15.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        searchKategori();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
