package ui.Master;

import java.awt.Color;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import dao.PeriodeDAO;
import model.Periode;

/**
 * Dialog untuk browsing data periode
 */
public class BrowsePeriodeDialog extends javax.swing.JDialog {
    private DefaultTableModel data;
    private PeriodeDAO periodeDAO;

    /**
     * Creates new form BrowsePeriodeDialog
     */
    public BrowsePeriodeDialog(java.awt.Frame parent, boolean modal, PeriodeDAO periodeDAO) {
        super(parent, modal);
        initComponents();
        this.periodeDAO = periodeDAO; // Inisialisasi periodeDAO
        tableCustom();  // Customisasi tabel
        loadPeriodeData();  // Load data periode
    }

    // Fungsi untuk meng-custom JTable
    private void tableCustom() {
        Object header[] = {"No", "Kode", "Tanggal Awal", "Tanggal Akhir", "Status", "Keterangan", "Aktif"}; 

        // Initialize the DefaultTableModel with header
        data = new DefaultTableModel(null, header);
        jTable1.setModel(data);

        // Configure the column widths for jTable1
        TableColumnModel columnModel = jTable1.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(30); // No
        columnModel.getColumn(1).setPreferredWidth(60); // Kode
        columnModel.getColumn(2).setPreferredWidth(100); // Tanggal Awal
        columnModel.getColumn(3).setPreferredWidth(100); // Tanggal Akhir
        columnModel.getColumn(4).setPreferredWidth(100); // Status
        columnModel.getColumn(5).setPreferredWidth(200); // Keterangan
        columnModel.getColumn(6).setPreferredWidth(50); // Aktif

        // Disable auto-resize
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        // Set background color
        jTable1.setBackground(Color.WHITE);
        jTable1.setGridColor(Color.GRAY); // Optional: to set the color of the grid lines

        // Set the table header background color
        jTable1.getTableHeader().setBackground(Color.LIGHT_GRAY);
        jTable1.getTableHeader().setForeground(Color.BLACK); // Optional: to set the text color in header

        // Set row height
        jTable1.setRowHeight(30); // Set height of rows
    }

    // Fungsi untuk memuat data periode dari database
    private void loadPeriodeData() {
        List<Periode> periodeList = periodeDAO.getAllPeriode();
        data.setRowCount(0); // Clear existing rows
        for (int i = 0; i < periodeList.size(); i++) {
            Periode periode = periodeList.get(i);
            data.addRow(new Object[]{
                i + 1, // No
                periode.getKode(),
                periode.getTanggalAwal(),
                periode.getTanggalAkhir(),
                periode.getStatus(),
                periode.getKeterangan(),
                periode.isAktif() ? "Ya" : "Tidak"
            });
        }
    }

    // Fungsi untuk mengambil JTable
    public JTable getTableBarang() {
        return jTable1;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Cari");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 276, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
